apiVersion: apps/v1
kind: Service
metadata:
  name: webapp-svc
  labels:
    app: webapp-svc
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30080
  selector:
    app: webapp-svc
  type: LoadBalancer
  